---
url: 'https://ericbanisadr.com'
collections:
  blog:
    output: true
    permalink: /:collection/:name
  cookbook:
    output: true
    permalink: /:collection/:name
defaults:
  -
    scope:
      path: ""
      type: "cookbook"
    values:
      layout: "recipe"
---
